server:
  port: 2020

spring:
  application:
    name: payment-service


  datasource:
    url: jdbc:mysql://localhost:3306/microservicesdb
    username: root
    password: vikas@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1010/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

